### ISSUE TITLE
what's the intent of this project?

### ISSUE THREAD

**Issue by montagy** [fhsjaagshs/niagra#1]
is it a preprocessor like clay?
what's the different?

**Comment by natesymer** [comment]
This is literally a rewrite of clay. That's the idea. The only difference (besides surface-level differences) is that it uses a faster builder module. Why do you ask?

**Comment by montagy** [comment]
maybe what i want is a readme file.
i read the example code,and think it's very good.
so i ask a question instead of read the source code.
